package controller;

import java.util.List;
import java.util.Map; // Import Map

import model.KhachHang;
import service.KhachHangService;

public class KhachHangController {
    // private KhachHangDAO khachHangDAO; // Should not directly use DAO here
    private KhachHangService khachHangService;

    public KhachHangController() {
        // this.khachHangDAO = new KhachHangDAO(); // Initialize service instead
        this.khachHangService = new KhachHangService();
    }

    public List<KhachHang> getAllKhachHang() {
        // return khachHangDAO.getAllKhachHang();
        return khachHangService.getAllKhachHang();
    }

    public KhachHang getKhachHangByMa(String maKH) {
        // return khachHangDAO.getKhachHangByMa(maKH);
        return khachHangService.getKhachHangByMa(maKH);
    }

    /**
     * Adds a new customer. MaTK should be pre-set on the KhachHang object if
     * generated by UI/Utils.
     * The defaultPassword is for the TAIKHOAN table, handled by service if
     * applicable.
     * 
     * @param kh              The KhachHang object.
     * @param defaultPassword The default password for the new account (can be null
     *                        if not creating account here).
     * @return The generated MaKH if successful, null otherwise.
     */
    public String addKhachHang(KhachHang kh, String defaultPassword) {
        // This method signature was from a previous response.
        // If TaiKhoanUtils was removed, the password might not be relevant here.
        // The service's addKhachHang should handle all logic.
        return khachHangService.addKhachHang(kh); // Assuming service handles MaTK and password if needed
    }

    // Overload for when password is not handled at this stage or TaiKhoanUtils is
    // not used
    public String addKhachHang(KhachHang kh) {
        return khachHangService.addKhachHang(kh);
    }

    public String getErrorMessage() {
        return khachHangService.getErrorMessage();
    }

    public boolean updateKhachHang(KhachHang kh) {
        return khachHangService.updateKhachHang(kh);
    }

    public boolean deleteKhachHang(String maKH) {
        return khachHangService.deleteKhachHang(maKH);
    }

    public List<KhachHang> searchKhachHang(String keyword) {
        return khachHangService.searchKhachHang(keyword);
    }

    public boolean isPhoneNumberExists(String sdt, String excludeMaKH) {
        return khachHangService.isPhoneNumberExists(sdt, excludeMaKH);
    }

    public boolean isEmailExists(String email, String excludeMaKH) {
        return khachHangService.isEmailExists(email, excludeMaKH);
    }

    public boolean isCCCDExists(String cccd, String excludeMaKH) {
        return khachHangService.isCCCDExists(cccd, excludeMaKH);
    }

    // private boolean validateKhachHang(KhachHang kh) {
    // Validation should be primarily in the service layer
    // return true; // Or call service validation
    // }

    // Phương thức mới để lấy thống kê
    public Map<String, Object> getThongKeKhachHang() {
        return khachHangService.getThongKeKhachHang();
    }
}